### ISSUE TITLE
 undefined method `normalize_attribute'

### ISSUE THREAD

**Issue by jperry** [mdeering/attribute_normalizer#49]
I am using rails 3.2.8 and 1.1.0 version of attribute_normalizer.  I am seeing this error when I create an instance of my model class using ActiveModel.
```
undefined method `normalize_attribute'
```

I am using this in my initializer file:

```ruby
AttributeNormalizer.configure do |config|
  config.normalizers[:subnets] = lambda do |value, options|
    value.join(',')
  end
end
```

Then in my model file I am using
```
include ActiveModel::AttributeMethods
include ActiveModel::Validations
include ActiveModel::Conversion
extend ActiveModel::Naming
extend ActiveModel::Translation
extend ActiveModel::Callbacks

normalize_attribute :subnets, :with => :subnets
```

**Comment by mdeering** [comment]
The whole idea behind the gem is to clean attribute data as it comes in through the standard classes setter interface.  So yes it does need to have the setter, getters should be optional.
