### ISSUE TITLE
Normalize empty json string to "{}"

### ISSUE THREAD

**Issue by JoshuaKolden** [mdeering/attribute_normalizer#51]
I created a custom normalizer:

```ruby
  config.normalizers[:json] = lambda do |text, options|
    if text == ""
      {}.to_json # or "{}"
    else
      text
    end
  end
```

But the spec fails oddly:
`  it { should normalize_attribute(:rawInfo).from("").to({}.to_json) }`
...
```
Failure/Error: it { should normalize_attribute(:rawInfo).from("").to({}.to_json) }
       rawInfo did not normalize as expected! "{}" != "{}"
```

I've checked the text encoding format of my source files, and used .to_json, also to eliminate that as in issue.  This is only an issue for the spec helper, or something else?

Thanks,
j

**Comment by mdeering** [comment]
closing as we both seem to be extremely busy for over a year :).  Reopen at any time if you can reproduce off of master.
