### ISSUE TITLE
Attribute normalizer should throw error if it trying to normalize an attribute that has already been

### ISSUE THREAD

**Issue by chrismitchell** [mdeering/attribute_normalizer#52]
For example if the we had:

```ruby
normalize_attributes :email, :first_name, :last_name
```
calling normalize_attribute on email, first_name, or last_name again should fail

**Comment by mdeering** [comment]
Not sure I agree with this anymore.  Agree with @PikachuEXE 's points and don't want the gem to work to hard to cover up for other bad programming practices.
