### ISSUE TITLE
Triggering all normalizers manually?

### ISSUE THREAD

**Issue by gamov** [mdeering/attribute_normalizer#57]
I would like to trigger manually all the normalizers, is it currently possible?
My use case is a form object using Structs as items.
I use the constructor to pass all the attributes from the params hash instead of using each attribute= methods, therefore attribute_normalizer is not triggered.

```ruby
class SDOwnUseItem < Struct.new(:name, :packaging, :uom, :um3, :uweight)
  include AttributeNormalizer
  normalize_attributes :name, :packaging
end
#usage
SDOwnUseItem.new(attributes.slice(:name, :packaging, :uom, :um3, :uweight)) #<- I would like this to trigger the normalisation
```

**Comment by trappist** [comment]
+1 to this feature request, adding normalization after you've already got data is probably a common use case.

**Comment by mdeering** [comment]
Performing normalization on any existing data IMHO should be a one time thing done in a script and not belong as a core part of you application or this gem.

Working from part of @rusterholz example above and assuming an ActiveRecord type of interface on your classes.

```ruby
CLASSES_IN_NEED_OF_NORMALIZATION = {
  ClassNumber1 => [:attribute_to_nomalize, :other_attribute_to_normalize],
  ClassNumber2 => [:yet_another_attribute_to_nomalize]
}

BATCH_SIZE = 100

CLASSES_IN_NEED_OF_NORMALIZATION.each do |class_to_normalize, attributes_to_normalize|
  puts "Starting the normalization process on #{class_to_normalize}"
  class_to_normalize.find_in_batches(batch_size: BATCH_SIZE).each do |batch|
    batch.each do |object|
      puts "Attempting to normalize:#{object}"
      attributes_to_normalize.each do |attribute|
        object.send("#{attribute}=", object.send(attribute))
      end
      object.save!
    end
  end
end
```

In no way tested but should give you the general idea of how I would first try to tackle it in a stand alone throw away script.
