### ISSUE TITLE
RSpecMatcher is out of date

### ISSUE THREAD

**Issue by rusterholz** [mdeering/attribute_normalizer#58]
Under rails 4.1.1, attribute_normalizer 1.1.0, and rspec 3.0.1, I get the following deprecation warning:

"AttributeNormalizer::RSpecMatcher::NormalizeAttribute implements a legacy RSpec matcher protocol. For the current protocol you should expose the failure messages via the `failure_message` and `failure_message_when_negated` methods."

**Comment by mdeering** [comment]
Matcher did get fixed with other pull requests.
