### ISSUE TITLE
destroy() breaking on model with has_and_belongs_to_many association to join table

### ISSUE THREAD

**Issue by mwalsher** [mdeering/attribute_normalizer#66]
Thought this was an odd rails bug in 4.1.5, but it turned out to be related to your gem with version 1.1.

I updated to master and that seems to fix it. Just thought I'd let you know.

https://github.com/rails/rails/issues/16732

**Comment by mdeering** [comment]
Offending code around _default_attributes_ has been removed and released in 1.2.  Marking this issues closed but tagging with _default_attributes_ as a test case if someone cares to restore that behaviour.
