### ISSUE TITLE
Default attributes?

### ISSUE THREAD

**Issue by mauriciopasquier** [mdeering/attribute_normalizer#69]
I was writing a PR (here's [my branch](/mauriciopasquier/attribute_normalizer/tree/always-apply-defaults) with failing tests) about default attributes not beign applied, but then I ran into [the commented-out code](/mdeering/attribute_normalizer/blob/master/lib/attribute_normalizer/model_inclusions.rb#L75-L80) and [this commit](/mdeering/attribute_normalizer/commit/ca56593e05a0eebc488183764120da6317e16298). I liked the idea of default attributes but if this is the direction the gem is going, at least we should fix the readme and deprecate the setter in the configuration.

**Comment by mdeering** [comment]
I have removed the idea of default attribute normalization and will not be restoring it as it is not a feature that I used.  It is not that the idea itself is bad or anything it is that the way that it is implemented caused issues, I believe AR abstract class was one scenario but there were also others also.

I would accept a pull request with a different implementation of it in the future.

I have removed it from the README on master.  Thanks for catching that.
