### ISSUE TITLE
:postal_code normalizer?

### ISSUE THREAD

**Issue by jbabe** [mdeering/attribute_normalizer#71]
@mdeering - we are going to be using your gem across quite a few of our apps...I'm planning on adding something simple that strips everything except letters and numbers for Canadian postal codes.

Any chance this would be something you pull in? If so, I'll create a PR. If not, I'll probably create an extension of this gem to avoid adding the same initializer to each one of our apps.

Thanks!

**Comment by mdeering** [comment]
@jbabe There is no need to extend the gem. You can just add the *postal_code* normalizer in an initializer like so.

```ruby
# config/initializers/attribute_normalizer.rb
AttributeNormalizer.configure do |config|

  config.normalizers[:postal_code] = lambda do |value, options|
    # Double check my RegExp ;)
    value.is_a?(String) ? value.gsub(/[^a-zA-Z0-9\.]+/, '').upcase : value
  end 

end
```

The use it in your model(s) like so

```ruby
# spec/models/address_spec.rb
require 'rails_helper'

RSpec.descibe Address do
  it { should normalize_attribute(:postal_code) }
  it { should normalize_attribute(:postal_code).from('v8x 3x4').to('V8X3X4') }
end
```

```ruby
class Address < ActiveRecord::Base
  # ...
  # choose one of the below options depending on how implement you postal_code
  # normalizer above and the behaviour you want.
  normalize_attribute :postal_code, with: [:strip, :blank, :postal_code]
  normalize_attribute :postal_code, with: :postal_code
  normalize_attribute :postal_code, after: :postal_code
  # ...
end

**Comment by mdeering** [comment]
@jbabe just clued in your from Edmonton! Say hi  :hand: to @ryanjones for me

**Comment by jbabe** [comment]
Thanks for writing the gem - it's pretty slick! I'll say hi to @ryanjones

Since we are using this across half a dozen apps I was wanting to avoid the initializer, so I've created an extension that will have a collection of normalizers specific to us: https://github.com/amaabca/attribute_normalizer-extras
