### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rafaelsales** [mdeering/attribute_normalizer#79]

**Comment by mdeering** [comment]
Yes, I do still use this gem on many production apps and any new Rails application I create.

**Comment by rafaelsales** [comment]
Yeah, just asked because I didn't see Rails 4 in README and the last issue filed. Thanks!

**Comment by mdeering** [comment]
All good. All my production apps are on the latest of 4.2 and have many side projects on 5 with no issues.

**Comment by rafaelsales** [comment]
Awesome, gonna use it! ;)
